services:
  # 1. Banco de Dados Relacional (Operacional)
  postgres:
    image: postgres:16-alpine
    container_name: corewms_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - corewms_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # 2. Banco de Dados NoSQL (Logs de Auditoria)
  mongodb:
    image: mongo:7.0
    container_name: corewms_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - corewms_mongo_data:/data/db
    restart: unless-stopped

  # 3. Nosso Backend (A API .NET 10)
  corewms-api:
    container_name: corewms_api
    build:
      context: ./CoreWMS.Api
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # A porta 5000 da sua máquina vai apontar para a 8080 do container
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # Vamos injetar as strings de conexão via variáveis de ambiente
      - ConnectionStrings__Postgres=Host=postgres;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - ConnectionStrings__MongoDb=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/?authSource=admin
    depends_on:
      - postgres
      - mongodb
    restart: unless-stopped

  frontend:
    container_name: corewms_frontend
    build:
      context: ./wms-frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5000
    ports:
      - "3000:80"
    depends_on:
      - corewms-api
    restart: unless-stopped

# Volumes nomeados para persistir os dados dos bancos caso os containers sejam recriados
volumes:
  corewms_postgres_data:
  corewms_mongo_data: