<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <!-- Ativa suporte a Windows Forms apenas se compilado para Windows -->
        <TargetFramework Condition="$([MSBuild]::IsOSPlatform('Windows'))">net10.0-windows</TargetFramework>
        <TargetFramework Condition="!$([MSBuild]::IsOSPlatform('Windows'))">net10.0</TargetFramework>
        <UseWindowsForms Condition="'$(TargetFramework)' == 'net10.0-windows'">true</UseWindowsForms>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.0" />
        <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.WindowsServices" Version="10.0.0" />
        <PackageReference Include="Microsoft.Extensions.Hosting.Systemd" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
        <None Update="index.html">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>